export const data = [{
    id: 1,
    title: "app_v1",
    last_edit: '6',
    isDeployed: false
}, {
    id: 2,
    title: "app_v2",
    last_edit: '76',
    isDeployed: true
}, {
    id: 3,
    title: "app_v11",
    last_edit: '21',
    isDeployed: true
}, {
    id: 4,
    title: "app_v3",
    last_edit: '92',
    isDeployed: false
}, {
    id: 5,
    title: "app_v112",
    last_edit: '12',
    isDeployed: false
}, {
    id: 6,
    title: "app_v51",
    last_edit: '45',
    isDeployed: false
}, {
    id: 7,
    title: "app_v71",
    last_edit: '90',
    isDeployed: false
}, {
    id: 8,
    title: "app_v81",
    last_edit: '622',
    isDeployed: false
}
]